"""LangGraph flow for the sidecar's conversation.

Owns the conversation as a real message list. Older turns are summarized once
the request approaches `models.context_tokens()`, so the whole conversation
stays available to the model instead of being truncated by a fixed window.
"""

from __future__ import annotations

import base64
import functools
import re
import struct
import sys
from typing import Iterator, TypedDict

from langchain.agents.middleware import SummarizationMiddleware
from langchain.agents.middleware.summarization import count_tokens_approximately
from langchain_core.messages import (
    AIMessage,
    HumanMessage,
    RemoveMessage,
    SystemMessage,
    ToolMessage,
)
from langgraph.graph import END, StateGraph
from langgraph.runtime import Runtime

import models
import tools

# Tools hand back PNG only, so the mime type is fixed here. Add a protocol field
# if a tool ever returns another format.
MIME = "image/png"

# Rounds of tool calls allowed in one request. The C++ host caps tool calls the
# same way, and its per-request deadline has to stay long enough for this many
# rounds plus their model latencies, or a long turn dies on "sidecar timed out"
# instead. Both caps move together.
MAX_TOOL_ROUNDS = 100000

# Said to the model once the rounds above are spent. With the tools withdrawn it
# otherwise reaches for one anyway and writes the call into its answer as text.
NO_TOOLS_NOTE = (
    "The tool budget for this request is exhausted. Answer in plain text now and "
    "do not emit any tool call markup."
)

# DeepSeek writes tool-call syntax into the text content when it wants a tool it
# was not offered. Nothing else contains the token "DSML", so tags carrying it
# are markup rather than answer: a whole block goes first, then any orphan half.
_DSML_BLOCK = re.compile(r"<[^>]*DSML[^>]*>.*?</[^>]*DSML[^>]*>",
                         re.IGNORECASE | re.DOTALL)
_DSML_TAG = re.compile(r"</?[^>]*DSML[^>]*>", re.IGNORECASE)


class TurnState(TypedDict, total=False):
    text: str       # request: this turn's instruction
    tools: list     # request: OpenAI tool schemas, generated by the C++ host
    messages: list  # built by build_messages
    tool_rounds: int
    reply: str      # response: model output
    turns: int      # response: turns retained in the conversation
    error: str


# Only the NDJSON read loop touches this, so it needs no lock.
_MESSAGES: list = []

# The screenshots this session can still cut a template out of, by the number
# their caption showed. Kept out of _MESSAGES on purpose: a picture in the
# history is re-sent on every later request and eventually summarized away,
# while the model only needs the *number* to be able to point at an old frame
# (cutting a dialog it already tapped away). Unbounded, cleared per session.
_IMAGES: dict[int, str] = {}
_NEXT_SHOT = 0

# Built lazily: both the budget and the model come from the environment, which
# main.py loads from llm/.env before the first request. A summary lands in
# _MESSAGES as the first HumanMessage, never as a SystemMessage: the summarizer
# drops those, so build_messages prepends the prompt instead.
_MW = None


def reset_history() -> None:
    """Drop every turn. The next request starts a fresh conversation."""
    global _MW, _NEXT_SHOT
    _MESSAGES.clear()
    _IMAGES.clear()
    _NEXT_SHOT = 0
    _MW = None


def history_size() -> int:
    """Turns currently kept verbatim; a summary does not count as a turn."""
    return sum(1 for m in _MESSAGES if isinstance(m, AIMessage))


def _middleware():
    """Summarizes older turns once the request approaches the budget.

    `keep` is a quarter of the budget. The history is text only -- screenshots
    live in `_IMAGES` and only the latest one is re-sent, by `build_messages` --
    so a quarter already covers many turns.
    """
    global _MW
    if _MW is None:
        counter = functools.partial(
            count_tokens_approximately, tokens_per_image=models.TOKENS_PER_IMAGE
        )
        budget = models.context_tokens()
        _MW = SummarizationMiddleware(
            model=models.build_chat_model(),
            trigger=("tokens", budget),
            keep=("tokens", budget // 4),
            token_counter=counter,
        )
    return _MW


def _content_to_text(content: object) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict) and block.get("type") == "text":
                parts.append(str(block.get("text", "")))
        return "".join(parts)
    return str(content)


def precheck(state: TurnState) -> dict:
    """A turn needs an instruction; whitespace alone is an empty request.

    Rejected here rather than at the model, so a stray space in the input box
    never turns into a paid round trip.
    """
    text = (state.get("text") or "").strip()
    if not text:
        return {"error": "empty request"}
    return {"text": text}


def compact(state: TurnState) -> dict:
    """Fold the oldest turns into a rolling summary once past the budget.

    Summarizing rewrites the request prefix, which invalidates the provider's
    prompt cache from that point on, so the summarizer's own hysteresis is what
    keeps this rare. A failure here is skipped, never fatal: the request is
    still far below the model's real limit, so it goes out unsummarized.
    """
    if not _MESSAGES:
        return {}
    try:
        out = _middleware().before_model({"messages": list(_MESSAGES)}, Runtime())
    except Exception as exc:  # noqa: BLE001 - summarizing must not lose history
        print(f"[sidecar] summarization skipped: {exc}", file=sys.stderr)
        return {}
    if not out or "messages" not in out:
        return {}
    # Drop the RemoveMessage sentinel: it signals a reducer this list has none of.
    _MESSAGES[:] = [m for m in out["messages"] if not isinstance(m, RemoveMessage)]
    return {}


def build_messages(state: TurnState) -> dict:
    """Assemble the model input from the conversation plus the current turn.

    The most recent screenshot rides along as its own user turn, so a request
    that follows a turn full of taps still opens on the screen the model last
    looked at. Only the latest one: older frames stay in `_IMAGES` to be cut
    from, not to be re-sent, and the prefix above stays byte-identical for the
    provider's prompt cache.
    """
    messages: list[object] = [SystemMessage(content=models.system_prompt())]
    messages.extend(_MESSAGES)
    latest = max(_IMAGES, default=0)
    if latest:
        messages.append(
            HumanMessage(content=_shot_content(
                latest, _shot_caption(latest, "The last screenshot you took:")))
        )
    messages.append(HumanMessage(content=state.get("text", "")))
    return {"messages": messages}


def strip_tool_markup(text: str) -> str:
    """Drop leaked tool-call markup, keeping whatever answer surrounds it."""
    cleaned = _DSML_TAG.sub("", _DSML_BLOCK.sub("", text))
    # A removed block leaves its own blank lines behind; one blank line is the
    # most an answer should show where the markup used to be.
    return re.sub(r"\n{3,}", "\n\n", cleaned).strip()


def invoke(state: TurnState) -> dict:
    """One model turn.

    The tool schemas come straight from the host and are passed to bind_tools
    unchanged, so the model sees exactly the signature C++ will enforce.
    """
    offered = state.get("tools") or []
    exhausted = bool(offered) and state.get("tool_rounds", 0) >= MAX_TOOL_ROUNDS
    try:
        model = models.build_chat_model()
        # Past the round cap the tools are withdrawn, so the model has to answer
        # in text instead of the request ending on an empty tool call.
        if offered and not exhausted:
            model = model.bind_tools(offered)
    except Exception as exc:  # noqa: BLE001 - surfaced to the caller as a result
        return {"error": str(exc)}

    model_input = list(state.get("messages") or [])
    if exhausted:
        # Withdrawing the tools silently is what produced raw markup in the
        # answer, so the withdrawal gets said out loud.
        model_input.append(HumanMessage(content=NO_TOOLS_NOTE))

    try:
        response = model.invoke(model_input)
    except Exception as exc:  # noqa: BLE001 - surfaced to the caller as a result
        return {"error": str(exc)}

    messages = list(state.get("messages") or [])
    messages.append(response)
    text = strip_tool_markup(_content_to_text(getattr(response, "content", response)))
    if not text and exhausted:
        # Tools are gone and the model said nothing usable, so say that rather
        # than showing an empty bubble the user would read as a hang. An empty
        # text on a normal round is just a round that only called tools.
        text = "The tool budget for this request is exhausted and the model gave " \
               "no text answer."
    # Accumulated across rounds: the UI streams every round's text, so keeping
    # only the last one would make the reply shrink when the turn completes.
    # A model that announces a tool call and then answers is the common case.
    prior = state.get("reply", "")
    if prior and text:
        reply = prior.rstrip() + "\n\n" + text
    else:
        reply = prior + text
    return {"messages": messages, "reply": reply}


def png_size(png_b64: str) -> tuple[int, int] | None:
    """Width and height of a base64 PNG, read from its fixed-position IHDR.

    The model names tap coordinates in these pixels, so it needs the exact size;
    the image alone does not state its own resolution.
    """
    # Signature (8) + chunk length (4) + "IHDR" (4) + width (4) + height (4) = 24
    # bytes, so the first 32 base64 characters already cover what we read.
    try:
        head = base64.b64decode(png_b64[:32])
    except ValueError:  # binascii.Error, for a payload that is not base64
        return None
    if len(head) < 24 or not head.startswith(b"\x89PNG\r\n\x1a\n"):
        return None
    return struct.unpack(">II", head[16:24])


def _store_shot(image_b64: str) -> int:
    """Files one screenshot under the next number and returns it.

    Numbers only ever go up, so a `shot` the model remembers from an earlier
    request keeps pointing at the same picture.
    """
    global _NEXT_SHOT
    _NEXT_SHOT += 1
    _IMAGES[_NEXT_SHOT] = image_b64
    return _NEXT_SHOT


def _shot_caption(shot: int, lead: str) -> str:
    """`lead` plus the number and size, which is what names this frame later.

    `save_template`'s `shot` is this number and its box is in these pixels, so
    both have to be on screen next to the picture.
    """
    size = png_size(_IMAGES[shot])
    return (f"{lead} #{shot} ({size[0]}x{size[1]} pixels)." if size
            else f"{lead} #{shot}.")


def _shot_content(shot: int, caption: str) -> list[dict]:
    """One numbered screenshot as user-turn content, for the model to look at.

    A user turn, never a tool result: ChatDeepSeek json.dumps()es list content
    on a `tool` message, so a data URL there is billed as text. One 1080x2400
    screenshot cost 2.3M tokens that way, against ~1k here.
    """
    return [
        {"type": "text", "text": caption},
        {"type": "image_url",
         "image_url": {"url": f"data:{MIME};base64,{_IMAGES[shot]}"}},
    ]


def run_tools(state: TurnState) -> dict:
    """Run the tool calls the model just asked for, one by one.

    Every call is executed by the host, and a failure is reported back to the
    model as the tool's result rather than raised, so it can correct itself on
    the next round.
    """
    messages = list(state.get("messages") or [])
    calls = getattr(messages[-1], "tool_calls", None) or []
    results: list = []
    for call in calls:
        name = call.get("name", "")
        args = call.get("args") or {}
        # Resolved before the round's own screenshot is stored: the model cannot
        # name a number that does not exist yet, and a stale one must not point
        # at the picture this very round is about to produce.
        reply = tools.call_cpp(name, args, tools.resolve_shot(args, _IMAGES))
        if reply.get("ok"):
            content: object = reply.get("text") or "ok"
        else:
            content = "error: " + str(reply.get("error", ""))
        results.append(ToolMessage(content=content, tool_call_id=call.get("id", "")))
        image = reply.get("image_b64") or ""
        if not image:
            continue
        if name == "screenshot":
            shot = _store_shot(image)
            results.append(
                HumanMessage(content=_shot_content(
                    shot, _shot_caption(shot, "Screenshot")))
            )
        else:
            # Every other image tool returns a marked-up copy for the user to
            # look at. It is not stored: its box and label would be baked into
            # any template cut from it.
            results.append(
                HumanMessage(content=[
                    {"type": "text", "text": f"Image after {name}."},
                    {"type": "image_url",
                     "image_url": {"url": f"data:{MIME};base64,{image}"}},
                ])
            )
    return {"messages": messages + results,
            "tool_rounds": state.get("tool_rounds", 0) + 1}


def route_after_invoke(state: TurnState) -> str:
    if state.get("error"):
        return "commit"
    messages = state.get("messages") or []
    calls = getattr(messages[-1], "tool_calls", None) if messages else None
    if not calls:
        return "commit"
    if state.get("tool_rounds", 0) >= MAX_TOOL_ROUNDS:
        return "commit"
    return "run_tools"


def commit(state: TurnState) -> dict:
    """Record the turn on success.

    A failed turn is deliberately not recorded, so retrying cannot pollute the
    context with a broken exchange. Nothing is trimmed here: `compact` owns
    that, and only once the budget is reached.
    """
    if state.get("error"):
        return {"turns": history_size()}

    _MESSAGES.append(HumanMessage(content=state.get("text", "")))
    _MESSAGES.append(AIMessage(content=state.get("reply", "")))
    return {"turns": history_size()}


def route_after_precheck(state: TurnState) -> str:
    return "end" if state.get("error") else "compact"


def build_graph():
    graph = StateGraph(TurnState)
    graph.add_node("precheck", precheck)
    graph.add_node("compact", compact)
    graph.add_node("build_messages", build_messages)
    graph.add_node("invoke", invoke)
    graph.add_node("run_tools", run_tools)
    graph.add_node("commit", commit)
    graph.set_entry_point("precheck")
    graph.add_conditional_edges(
        "precheck", route_after_precheck, {"compact": "compact", "end": END}
    )
    graph.add_edge("compact", "build_messages")
    graph.add_edge("build_messages", "invoke")
    graph.add_conditional_edges(
        "invoke",
        route_after_invoke,
        {"run_tools": "run_tools", "commit": "commit"},
    )
    # Another model turn, with the results now in the message list.
    graph.add_edge("run_tools", "invoke")
    graph.add_edge("commit", END)
    return graph.compile()


_GRAPH = None


def stream_turn(state: TurnState,
                out_state: dict) -> Iterator[tuple[bool, str]]:
    """Run the graph, yielding (is_answer, text) and copying the final state.

    (True, delta) is answer text to display; (False, "") is a reasoning
    heartbeat, meaning the model is thinking and has no answer yet. The final
    state lands in `out_state` for `error` and `turns`, which only exist once
    the run is over.
    """
    global _GRAPH
    if _GRAPH is None:
        _GRAPH = build_graph()
    for mode, payload in _GRAPH.stream(state, stream_mode=["messages", "values"]):
        if mode == "values":
            out_state.update(payload)
            continue
        chunk, meta = payload
        # Both the input echo (build_messages) and the summarizer (compact)
        # stream chunks too; only invoke is the answer.
        if meta.get("langgraph_node") != "invoke":
            continue
        text = _content_to_text(getattr(chunk, "content", ""))
        yield (bool(text), text)
