#!/usr/bin/env python3
"""CampCat LLM sidecar: NDJSON over stdin/stdout.

Owns all model configuration; the C++ host only sends the user's instruction and
reads back text, executing any tool call the model asks for.

Usage:
  python3 llm/main.py           # persistent: print `ready`, then serve requests
  python3 llm/main.py --once    # read one request line, print one result, exit
"""

from __future__ import annotations

import pathlib
import sys
import time
import traceback
from typing import Iterator

import graph
import models
import protocol
import transport

# Deltas are flushed at most this often. Batching keeps one long answer from
# turning into a few hundred NDJSON lines on stdout.
BATCH_SECONDS = 0.05


def handle_request(req: dict) -> Iterator[dict]:
    """Turn one decoded request into one or more response messages."""
    rtype = req.get("type")
    rid = req.get("id")
    # Recorded so a tool call made deep inside the graph echoes the right id.
    transport.set_current_rid(rid)

    if rtype == "ping":
        yield protocol.build_result(rid, True, "pong")
        return
    if rtype == "reset":
        graph.reset_history()
        yield protocol.build_result(rid, True, turns=0)
        return
    if rtype == "memorize":
        # The conversation is already here, so only the current notes cross the
        # wire; the reply carries the rewritten ones back for the host to write.
        notes = graph.memorize(req.get("memory") or "")
        if notes is None:
            yield protocol.build_error_result(rid, "memory not updated")
        else:
            yield protocol.build_result(rid, True, notes)
        return
    if rtype != "turn":
        yield protocol.build_log("warn", f"ignoring unknown message type: {rtype}")
        return

    out: dict = {}
    buf: list[str] = []
    thinking_sent = False
    last = time.monotonic()
    try:
        for is_answer, text in graph.stream_turn(
            {
                "text": req.get("text") or "",
                # Generated by reflection on the C++ side; passed through
                # untouched so the model sees the signatures C++ enforces.
                "tools": req.get("tools") or [],
                # Long-term notes, read off disk by the host this turn.
                "memory": req.get("memory") or "",
            },
            out,
        ):
            if not is_answer:
                # Sent at once rather than batched, or the hint would arrive
                # only after the thinking it is meant to announce.
                if not thinking_sent:
                    thinking_sent = True
                    yield protocol.build_chunk(rid, thinking=True)
                continue
            buf.append(text)
            now = time.monotonic()
            if now - last >= BATCH_SECONDS:
                yield protocol.build_chunk(rid, "".join(buf))
                buf.clear()
                last = now
    except Exception as exc:  # noqa: BLE001 - never let a request kill the loop
        traceback.print_exc(file=sys.stderr)
        yield protocol.build_error_result(rid, str(exc))
        return

    if buf:
        yield protocol.build_chunk(rid, "".join(buf))
    if out.get("error"):
        yield protocol.build_error_result(rid, str(out["error"]))
        return
    yield protocol.build_result(
        rid, True, str(out.get("reply", "")), turns=out.get("turns")
    )


def emit(msg: dict) -> None:
    transport.emit(msg)


def main(argv: list[str]) -> int:
    once = "--once" in argv

    applied = models.load_env_file(pathlib.Path(__file__).resolve().parent / ".env")
    if applied:
        print(f"[sidecar] loaded {applied} var(s) from llm/.env", file=sys.stderr)

    if not once:
        emit(protocol.build_ready())

    # readline() rather than `for line in sys.stdin`: the iterator reads ahead,
    # which would swallow the host's answer to a tool call made mid-request.
    while True:
        line = sys.stdin.readline()
        if not line:
            break
        req = protocol.decode(line)
        if req is None:
            continue
        for msg in handle_request(req):
            emit(msg)
        if once:
            break

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except SystemExit:
        raise
    except BaseException:  # noqa: BLE001 - fatal: report on stderr only
        traceback.print_exc(file=sys.stderr)
        raise SystemExit(1)
