"""Bridge to the C++ tool runner.

There are no tool implementations here, and no schemas. The schemas arrive with
each request, generated by reflection from the C++ declarations, and the call
runs where the device is (C++ `llm::dispatch`). This module only carries a
`tool_call` out and its `tool_result` back, so a tool can never end up with two
definitions that disagree.
"""

from __future__ import annotations

from uuid import uuid4

import protocol
import transport


def call_cpp(name: str, args: dict) -> dict:
    """Run one tool on the host and return its `tool_result` message.

    The host runs the call inline while it waits for its own request to finish,
    so this blocks for as long as the tool takes. There is no timeout here: the
    host's per-request budget is the bound, and it reports its own failure
    rather than leaving this waiting.
    """
    call_id = f"{name}-{uuid4().hex}"
    transport.emit(
        protocol.build_tool_call(transport.get_current_rid(), call_id, name, args)
    )
    while True:
        msg = transport.read_message()
        if msg is None:
            raise RuntimeError("host closed the stream during a tool call")
        if msg.get("type") == "tool_result" and msg.get("call_id") == call_id:
            return msg
        # `log` lines are the host narrating to itself. Anything else belongs to
        # the request loop, which is blocked inside this very call.
        if msg.get("type") != "log":
            transport.push_back(msg)
