#pragma once

#include <filesystem>
#include <functional>
#include <string>
#include <string_view>
#include <vector>

namespace campcat {
class adb_client;
struct app_config;
} // namespace campcat

namespace campcat::llm {

/// A box on the screen, in screenshot pixels. A plain aggregate on purpose: the
/// model never sees this type (`tap` takes four ints) and reflection,
/// the schema layer, does not know it.
struct rect {
  int x = 0; ///< 左上角 X，截图像素
  int y = 0; ///< 左上角 Y
  int w = 0; ///< 宽
  int h = 0; ///< 高
};

/// One question for the human, asked before a gated tool is allowed to run.
struct approval_request {
  std::string tool;            ///< 被闸的工具名，如 "tap"
  std::string summary;         ///< 给人看的一句话
  std::vector<rect> highlight; ///< 要在截图上画出的框
  std::string screen_png;      ///< 最近一次截图的原始 PNG 字节（不是 base64）；可能为空
};

/// How a human answered an approval_request. `guidance` is a correction, so it
/// only means anything when `approved` is false.
struct approval_decision {
  bool approved = false;
  std::string guidance;
};

/// The screenshot the model is working from. Raw PNG bytes (not base64): the wire
/// encoding happens once, on the way out. Both fields live and die together, and
/// outlive the turn they were taken in (see `current_screen`).
struct screen_state {
  int w = 0;
  int h = 0;
  std::string png;
};

/**
 * @brief Runtime state the tools read but the model must never see.
 *
 * The adb session is deliberately absent from every tool signature: it is
 * environment, not an argument. The screenshot under discussion is the same
 * kind of thing, and it outlives the turn: `llm_host` keeps it (see
 * `current_screen`) and injects it here each turn, so a tap at coordinates
 * taken from it stays valid until the model asks for a fresh one.
 */
struct tool_context {
  adb_client *adb = nullptr;
  /// True while an automation cycle owns adb, so tools must refuse rather than
  /// compete for the device. An empty function means "never busy".
  std::function<bool()> adb_busy;
  /// Last screenshot of the session; injected by `llm_host::run_turn`.
  screen_state screen;
  /// Gated tools ask the human through this. An empty function means there is
  /// nobody to ask, and the tool then refuses: a gate that silently opens is
  /// worse than no gate.
  std::function<approval_decision(const approval_request &)> request_approval;
  /// Mirrors app_config::require_tool_approval: whether the tools that change the
  /// device or write files (`tap`, `run_script`, `save_script`, `save_template`)
  /// ask the human before acting.
  bool require_approval = false;
  /// Config the script tools hand to the interpreter (matcher thresholds, pacing).
  /// Null makes `run_script` refuse rather than run with defaults nobody chose.
  const app_config *cfg = nullptr;
  /// Root a model-authored script's relative paths (template PNGs, `run`) resolve
  /// against. It has no file of its own, so this stands in for its directory.
  std::filesystem::path script_dir;
};

/// Outcome of one tool call. `image_png` is set only by image-returning tools
/// and holds raw PNG bytes; the host base64-encodes them for the wire, which is
/// the only place the encoding exists.
struct tool_reply {
  bool ok = false;
  std::string text;
  std::string error;
  std::string image_png;
  /// Line the UI's tool note shows instead of `text`; non-empty also marks the
  /// text as a document for the model, too long to print (see `js::quiet`).
  std::string_view quiet_note;
};

/// Sets the context every tool reads. Called once per turn by the worker that
/// runs the sidecar exchange; that same thread performs every dispatch, so no
/// lock is needed. Passing a default-constructed context disables the tools.
void set_context(const tool_context &_ctx);

/// The screenshot the tools currently hold: the one injected this turn, or the
/// one `screenshot` replaced it with. `run_turn` takes it back at the end of a
/// turn and injects it again next turn: the screenshot belongs to the session,
/// not to the turn.
void current_screen(screen_state *_out);

/// The OpenAI tools array, generated by reflection from the tool declarations.
std::string tools_json();

/// Runs one tool by name against the model's raw `arguments` JSON text.
/// Never throws: every failure comes back as `ok == false`.
///
/// `_image_b64` is a screenshot the sidecar kept from earlier in the session,
/// attached when the arguments ask for one (a `shot` number). Empty when the
/// call needs no picture, which is every call but `save_template`.
tool_reply dispatch(std::string_view _name, std::string_view _args_json,
                    std::string_view _image_b64 = "");

/// True while a script started by `run_script` is executing. The UI polls it to
/// decide whether its stop control is worth showing.
bool script_running();

/// Asks the script that is running to stop before its next statement. Safe to
/// call when nothing is running.
void request_script_stop();

} // namespace campcat::llm
