#pragma once

#include <functional>
#include <string>
#include <string_view>
#include <vector>

namespace campcat {
class adb_client;
} // namespace campcat

namespace campcat::llm {

/// A box on the screen, in screenshot pixels. A plain aggregate on purpose: the
/// model never sees this type (`request_tap` takes four ints) and reflection,
/// the schema layer, does not know it.
struct rect {
  int x = 0; ///< 左上角 X，截图像素
  int y = 0; ///< 左上角 Y
  int w = 0; ///< 宽
  int h = 0; ///< 高
};

/// One question for the human, asked before a gated tool is allowed to run.
struct approval_request {
  std::string tool;            ///< 被闸的工具名，如 "tap"
  std::string summary;         ///< 给人看的一句话
  std::vector<rect> highlight; ///< 要在截图上画出的框
  std::string screen_png;      ///< 最近一次截图的原始 PNG 字节（不是 base64）；可能为空
};

/// How a human answered an approval_request. `guidance` is a correction, so it
/// only means anything when `approved` is false.
struct approval_decision {
  bool approved = false;
  std::string guidance;
};

/**
 * @brief Runtime state the tools read but the model must never see.
 *
 * The adb session and the size of the screenshot under discussion are
 * deliberately absent from every tool signature: they are environment, not
 * arguments. `screen_w`/`screen_h` start unknown and a `screenshot` call fills
 * them in, so a tap before the model has looked at the screen is refused.
 */
struct tool_context {
  adb_client *adb = nullptr;
  /// True while an automation cycle owns adb, so tools must refuse rather than
  /// compete for the device. An empty function means "never busy".
  std::function<bool()> adb_busy;
  int screen_w = 0;
  int screen_h = 0;
  /// Gated tools ask the human through this. An empty function means there is
  /// nobody to ask, and the tool then refuses: a gate that silently opens is
  /// worse than no gate.
  std::function<approval_decision(const approval_request &)> request_approval;
  /// Mirrors app_config::require_tool_approval: decides whether approval tools
  /// enter the tool list and whether `tap` needs a grant.
  bool require_approval = false;
};

/// Outcome of one tool call. `image_png` is set only by image-returning tools
/// and holds raw PNG bytes; the host base64-encodes them for the wire, which is
/// the only place the encoding exists.
struct tool_reply {
  bool ok = false;
  std::string text;
  std::string error;
  std::string image_png;
};

/// Sets the context every tool reads. Called once per turn by the worker that
/// runs the sidecar exchange; that same thread performs every dispatch, so no
/// lock is needed. Passing a default-constructed context disables the tools.
void set_context(const tool_context &_ctx);

/// The OpenAI tools array, generated by reflection from the tool declarations.
std::string tools_json();

/// Runs one tool by name against the model's raw `arguments` JSON text.
/// Never throws: every failure comes back as `ok == false`.
tool_reply dispatch(std::string_view _name, std::string_view _args_json);

} // namespace campcat::llm
